# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.2.2.dev508+g2611c0d.d20230327"
__version_tuple__ = version_tuple = (0, 2, 2, "dev508", "g2611c0d.d20230327")
