name: Build and Deploy Sphinx Docs from Development

on:
  push:
    branches:
      - grd-pyclarity-doc  # Trigger only when pushing to 'development'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs docs/_build/html

      - name: Deploy to GitHub Pages (gh-pages-dev)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages-dev  # separate branch for preview
