# This workflow will run lint and many other pre-commit hooks
# https://pre-commit.com/

name: lint

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ['3.8', '3.9', '3.10']
    name: Lint and pre-commit checks
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        pip install pre-commit isort flake8==3.9.2
        pre-commit install
    - name: pre-commit
      run: |
        echo "Running pre-commit on all files..."
        echo ""
        pre-commit run --all-files
    - name: Advise on installing pre-commit
      run: |
        echo "pre-commit checks have failed."
        echo ""
        echo "Please consider installing and configuring pre-commit to run locally. To do so..."
        echo ""
        echo " pip install pyclarity.[dev]"
        echo " pre-commit install"
        echo ""
        echo "For more information please refer to https://claritychallenge.org/clarity/CONTRIBUTING.html"
      if: always() && (steps.pre-commit.outcome == 'failure')
